config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#homepage'

  resources :categories
  resources :products
  resources :figures
  resources :comments, except: [:new]
  resources :user_figures

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :products, only: [:show] do
    resources :figures, only: [:show]
  end
  
  resources :figures, only: [:show] do
    resources :comments, only: [:new, :show]
  end 

  get 'collection/:id', to: 'user_figures#show', as: 'collection'
 
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :figure

    validates :comment, presence: true, length: {maximum: 250}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authentication_required

    def new
        @figure = Figure.find(params[:figure_id])
        @comment = Comment.new(figure:@figure, user_id:session[:user_id])
        
    end
    
    def create
        @comment = Comment.new(comment_params)
        if @comment.valid?
            @comment.save
            redirect_to figure_comment_path(@comment.figure, @comment)
        else
            render :new
        end
    end

    def show
        @comment = Comment.find(params[:id])
        if params[:figure_id]
            figure = Figure.find_by(id: params[:figure_id])
            if @comment == nil || @comment.figure != figure
                redirect_to products_path, flash: {alert: "Figure not found. Try Again!"}
            end
        end
    end

    def edit
        @comment = Comment.find(params[:id])      
    end 
    
    def update
        @comment = Comment.find(params[:id])
    
        @comment.update(comment_params)
    
        if @comment.save
          redirect_to figure_comment_path(@comment.figure, @comment)
        else
          render :edit
        end
      end
    
      def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        flash[:notice] = "Comment deleted."
        redirect_to figure_path(@comment.figure)
      end

    private

    def comment_params
        params.require(:comment).permit(:comment, :user_id, :figure_id, )
    end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment  do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :figure_id %>
    <%= f.label :comment  %><br>
    <%= f.text_area :comment, :id => "message_area", :cols => 50, :rows => 10 %><br>

    <%= f.submit%>

   
    <%end%>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Create A Comment</h1>

<% if @comment.errors.any?%>
    <div id= "error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error")%> Error: </h2>
        <ul>
            <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <%end%>
        </ul>
    </div>
<%end%>

<%= render 'form' %> 

app/views/comments/show.html.erb
<div class="blue-box">
    <div class="white-background text-center m-4">
        <h2>Figure commented:</h2>
        <h2 class="m-4"><%= link_to @comment.figure.name, figure_path(@comment.figure) %></h1>
        <p class="m-2"><%= "Post by: #{@comment.user.username}" %></p>
        <h3><%= @comment.comment %></h3><br>

        <%  if current_user == @comment.user %> 
        <p class="m-2"><%= link_to "Edit Comment", edit_comment_path%>
        <p class="m-2"><%=link_to "Delete Comment", comment_path, method: "DELETE"%><p><br>
        <%end%>

        <p><%= link_to "Back to Figure", figure_path(@comment.figure) %><p>
    </div>
</div>