config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#homepage'

  resources :categories
  resources :products
  resources :figures
  resources :comments, except: [:new]
  resources :user_figures

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :products, only: [:show] do
    resources :figures, only: [:show]
  end
  
  resources :figures, only: [:show] do
    resources :comments, only: [:new, :show]
  end 

  get 'collection/:id', to: 'user_figures#show', as: 'collection'
 
end

app/models/figure.rb
class Figure < ApplicationRecord
    has_many :comments
    has_many :commenters, through: :comments, source: :user
    has_many :user_figures
    has_many :users, through: :user_figures
    belongs_to :product

    validates :name, presence: true

    def self.search_by_name(figure_name) 
        where('name LIKE ?', "%#{figure_name}%")#LIKE ? let you search for name same or similar to the user input
    end

    
    # def self.search_by_name(figure_name) 
    #     where(name: figure_name)
    # end
     

end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController
    before_action :authentication_required

    def index
        if params[:search].present? 
            @figures = Figure.search_by_name(params[:search])
        else
            @figures = Figure.all 
        end
    end
    
    
    def show
        @figure = Figure.find(params[:id])
        if params[:product_id]
            product = Product.find_by(id: params[:product_id])
            if @figure == nil || @figure.product != product
                redirect_to products_path, flash: {alert: "Figure not found. Try Again!"}
            end
        end
        @user_figure = UserFigure.find_or_initialize_by(figure: @figure, user: current_user)   
    end 

end

app/helpers/figures_helper.rb
module FiguresHelper
end

app/views/figures/index.html.erb
<div class="blue-box">
    <div class="white-background text-left">

        <p><%= link_to "Back to Homepage", user_path(current_user) %><p>
        <h1 class="m-4"> FUNKO POP FIGURES LIST </h1>
        <h2> Search by Figure Name </h2>
        <%= form_tag(figures_path, method: :get) do %>
            <%= search_field_tag :search %>
            <%= submit_tag "Search" %>
        <%end%>

        <% if @figures.any? %>
            <ul>
                <% @figures.each do |figure|%>
                    <li>
                    <h2 class="m-4"><%= link_to figure.name, figure_path(figure)%></h2>
                    <p><%= "#{figure.product.category.name}, #{figure.product.name}"%></p>
                    </li>
                <%end%>
            </ul>
        <% else %>
            <p class="mt-4">No figures found.</p>
        <% end %>
    </div>
</div>


    

app/views/figures/show.html.erb
<div class="blue-box">
    <div class="funko-background">
        <div class="white-background border border-primary  m-4">
            <div class="row">
                <div class="col-12 col-md-5 text-center">
                    <h1 class="m-4"><%= @figure.name%></h1>
                    <%=image_tag("figures/#{@figure.image_name}", class: "figure-image m-4")%>

                    <%= render "layouts/errors", object: @user_figure%>
                                
                    <% if @user_figure.user.figures.include?(@figure) %>
                        <p><%=link_to "Remove", user_figure_path(@user_figure), method: "DELETE"%><p>     
                    <%else%>
                        <%= form_for(@user_figure) do |f| %>
                            <%= f.hidden_field :user_id %>
                            <%= f.hidden_field :figure_id %>
                            <%= f.submit "Add To Your Collection", class: "btn btn-primary mb-3"%>
                        <%end%>
                    <%end%>
                </div>
                <div class="col-12 col-md-7">
                <h3 class="m-4"><%=link_to "Add a new comment", new_figure_comment_path(@figure)%><h3>

                <h1 class="m-3">Comments: </h1>
                <% @figure.comments.each do |comment|%>
                    <ul>
                        <li>
                            <% if current_user == comment.user %>
                                <h3><%= link_to comment.comment, figure_comment_path(comment.figure, comment) %></h3>
                                <p><%= "By: #{comment.user.username}" %></p>
                            <%else%>
                                <h3><%= comment.comment%></h3>
                                <p><%= "By: #{comment.user.username}" %></p>
                            <%end%>
                        </li>
                    </ul>
                <%end%>
            </div>
            </div>
            <p class="text-right"><%= link_to "Back to Catalog", products_path %><p>
            <p class="text-right"><%= link_to "Back to Homepage ", user_path(current_user) %><p>
        </div>
    </div>
</div>