config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#homepage'

  resources :categories
  resources :products
  resources :figures
  resources :comments, except: [:new]
  resources :user_figures

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :products, only: [:show] do
    resources :figures, only: [:show]
  end
  
  resources :figures, only: [:show] do
    resources :comments, only: [:new, :show]
  end 

  get 'collection/:id', to: 'user_figures#show', as: 'collection'
 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :comments
    has_many :commented_figures, through: :comments, source: :figure 
    has_many :user_figures
    has_many :figures, through: :user_figures

    validates :email, uniqueness: true
    validates :username, :email, presence: true
    

    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authentication_required, except: [:new, :create]

    def index
        @users = User.all
        
    end 
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id]) 
        @figure = @user.figures
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

     

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_collection.html.erb
<div class="blue-box">
    <div class="white-background text-left">
        <div class="row">
            <div class="col-12 col-md-5">
                <h2> Collection:</h2>
                <ul>
                    <% @user.user_figures.each do |user_figure|%>
                        <li>
                            <h2><%= link_to user_figure.figure.name, figure_path(user_figure.figure)%></h2>
                            <p><%= "#{user_figure.figure.product.category.name}, #{user_figure.figure.product.name}"%>
                            <% if current_user == @user %>
                            <p><%=link_to "Remove", user_figure_path(user_figure), method: "DELETE"%><p>
                            <%end%>
                        </li>
                    <%end%>
                </ul>
            </div>
            <div class="col-12 col-md-7">
                <h2><%= "Commented Figures by #{@user.username}:"%></h2>
                <ul> 
                    <% if @user.commented_figures.length == 0%>
                           <h3 class="alert alert-primary"> None </h3>
                    <%else%>
                        <% @user.commented_figures.uniq.each do |figure| %>
                            <li><h3><%= figure.name%></h3></li>
                        <%end%>   
                    <%end%>  
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="blue-box">
    <div class="white-background text-left">
        <p><%= link_to "Back to Homepage", user_path(current_user) %><p><br>
        <h1 class="m-4"> Meet our users! </h1>

        <% @users.each do |user|%>

            <% if user != current_user %>
                <ul>
                    <h2><li><%= link_to user.username, user_path(user)%></li></h2>
                </ul>
            <%end%>
        <%end%>
    </div>
</div>

app/views/users/new.html.erb
<div class="blue-box">
    <div class="white-background">
        <h1>Sign Up Here</h1>

        <%= render("layouts/errors", object: @user)%>


        <%= form_with(model: @user, url:'/signup', local: true) do |f|%>
            <div class="form-group">
                <%= f.label :username %>
                <%= f.text_field :username, class: "form-control"%>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <%= f.submit "Sign Up", class: "btn btn-primary mb-3"%>
        <% end %>

        <%= link_to "Back To Homepage", root_path%>
    </div>
</div>

app/views/users/show.html.erb
<div class="blue-box">
    <div class="funko-background">
        <div class="white-background text-center border border-primary m-4">

            <% if @user == current_user %>
            <h1 class="m-4">Welcome <%=@user.username%>!</h1>
            <%=image_tag("funko_image.png")%>


                <% if @figure.length == 0 %>
                    <h3 class="m-4"><%= link_to "Create your Funko POP Collection", products_path %></h3>
                <%else%>
                    <h1 class="m-4"> My Funko POP Collection: </h2>
                    <%= render 'collection' %>
                <% end%>

                <p class="m-4"><%= link_to "See all Funko POP Figures available", figures_path %></p>
                <p class="m-4"><%= link_to "See other users Collections!", users_path %></p>
                <p class="m-4"><%= link_to "Log out", logout_path, method: "delete" %></p>

            <% else %>
                <p><%= link_to "Back to all users", users_path %><p>
                <h1><%= @user.username%></h2>
                <%= render 'collection' %>
                
            
            <%end%>
        </div>
    </div>
</div>