config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#homepage'

  resources :categories
  resources :products
  resources :figures
  resources :comments, except: [:new]
  resources :user_figures

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :products, only: [:show] do
    resources :figures, only: [:show]
  end
  
  resources :figures, only: [:show] do
    resources :comments, only: [:new, :show]
  end 

  get 'collection/:id', to: 'user_figures#show', as: 'collection'
 
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :figures

    validates :name, presence: true
    
    def self.by_category(category_id)
        where(category: category_id)
    end

    def self.grouped(collection)
        collection.group_by{ |product| product.category.name}
    end
    
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authentication_required

    def index
        @categories = Category.all
        if !params[:category].blank?
            products_collection = Product.by_category(params[:category])
        else
            products_collection = Product.all
        end
        @products = Product.grouped(products_collection)
        
    end

    def show
        @product = Product.find(params[:id])
        @figures = Figure.where(product: params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="blue-box">
    <div class="funko-background">
        <div class="white-background text-center m-4">


            <p><%= link_to "Back to Homepage", user_path(current_user) %><p><br>

            <h1 class="font-weight-bold mb-4">Let's add some figures!!!</h1>
            <%=image_tag("banner.jpg", style:"width:100%;")%>
            <div>
              <h3 class="m-4">Categories List:</h3>
              <%= form_tag("/products", method: "get") do %>
                <%= select_tag "category", options_from_collection_for_select(@categories, "id", "name"), include_blank: true %>
                <%= submit_tag "Go", class: "btn btn-primary" %>
              <% end %>
            </div>


            <% @products.each do |category_name, products| %>
                <h2 class="m-4 font-weight-bold"><%= category_name %></h2>
                <% products.each do |product|%>
                  <h3 class="m-2"><%= link_to product.name, product_path(product) %></h3>
                <%end%>
                <%end%>
        </div>
    </div>
</div>


    
    
 

app/views/products/show.html.erb
<div class="blue-box">
        <div class="white-background text-center m-4">

            <h1 class="m-4"><%= @product.name %></h1>
            <% @figures.each do |figure| %>
            <h2 class="m-4"><%= link_to figure.name, product_figure_path(@product,figure) %></h2>
            <%end%>
            <p class="m-4"><%= link_to "Back to Catalog", products_path %><p>
        </div>
</div>